/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senai.sp.jandira.ui;

/**
 *
 * @author 22282211
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        LabelIcon = new javax.swing.JLabel();
        LabelText = new javax.swing.JLabel();
        Agenda = new javax.swing.JButton();
        Pacientes = new javax.swing.JButton();
        Medicos = new javax.swing.JButton();
        Especialidades = new javax.swing.JButton();
        PlanoDeSaude = new javax.swing.JButton();
        Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        HeaderPanel.setBackground(new java.awt.Color(0, 0, 102));
        HeaderPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        HeaderPanel.setLayout(null);

        LabelIcon.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        LabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/agenda64.png"))); // NOI18N
        HeaderPanel.add(LabelIcon);
        LabelIcon.setBounds(20, 10, 64, 70);

        LabelText.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        LabelText.setForeground(new java.awt.Color(255, 255, 255));
        LabelText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelText.setText("Sistema para Agendamento de Consultas");
        HeaderPanel.add(LabelText);
        LabelText.setBounds(90, 30, 410, 30);

        getContentPane().add(HeaderPanel);
        HeaderPanel.setBounds(0, 0, 800, 90);

        Agenda.setBackground(new java.awt.Color(102, 102, 102));
        Agenda.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Agenda.setForeground(new java.awt.Color(255, 255, 255));
        Agenda.setText("Agenda");
        Agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendaActionPerformed(evt);
            }
        });
        getContentPane().add(Agenda);
        Agenda.setBounds(10, 100, 120, 40);

        Pacientes.setBackground(new java.awt.Color(102, 102, 102));
        Pacientes.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Pacientes.setForeground(new java.awt.Color(255, 255, 255));
        Pacientes.setText("Pacientes");
        Pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacientesActionPerformed(evt);
            }
        });
        getContentPane().add(Pacientes);
        Pacientes.setBounds(140, 100, 120, 40);

        Medicos.setBackground(new java.awt.Color(102, 102, 102));
        Medicos.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Medicos.setForeground(new java.awt.Color(255, 255, 255));
        Medicos.setText("Médicos");
        Medicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicosActionPerformed(evt);
            }
        });
        getContentPane().add(Medicos);
        Medicos.setBounds(270, 100, 120, 40);

        Especialidades.setBackground(new java.awt.Color(102, 102, 102));
        Especialidades.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Especialidades.setForeground(new java.awt.Color(255, 255, 255));
        Especialidades.setText("Especialidades");
        Especialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecialidadesActionPerformed(evt);
            }
        });
        getContentPane().add(Especialidades);
        Especialidades.setBounds(400, 100, 120, 40);

        PlanoDeSaude.setBackground(new java.awt.Color(102, 102, 102));
        PlanoDeSaude.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        PlanoDeSaude.setForeground(new java.awt.Color(255, 255, 255));
        PlanoDeSaude.setText("Plano de Saúde");
        PlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanoDeSaudeActionPerformed(evt);
            }
        });
        getContentPane().add(PlanoDeSaude);
        PlanoDeSaude.setBounds(530, 100, 130, 40);

        Sair.setBackground(new java.awt.Color(102, 102, 102));
        Sair.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        Sair.setForeground(new java.awt.Color(255, 255, 255));
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair);
        Sair.setBounds(730, 100, 60, 40);

        setBounds(0, 0, 816, 468);
    }// </editor-fold>//GEN-END:initComponents

    private void PacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PacientesActionPerformed

    private void MedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicosActionPerformed

    private void EspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspecialidadesActionPerformed

    private void AgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgendaActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SairActionPerformed

    private void PlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanoDeSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlanoDeSaudeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agenda;
    private javax.swing.JButton Especialidades;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel LabelIcon;
    private javax.swing.JLabel LabelText;
    private javax.swing.JButton Medicos;
    private javax.swing.JButton Pacientes;
    private javax.swing.JButton PlanoDeSaude;
    private javax.swing.JButton Sair;
    // End of variables declaration//GEN-END:variables
}
